### PR TITLE
If LISTEN is a file path, listen on unix socket instead of tcp

### PR DESCRIPTION
**Pull request by squash**
This is a quick addition to allow listening on a unix socket. Useful for container proxying in small environments among other circumstances. LISTEN values starting with a "/" are assumed to be unix domain.

### CODE REVIEW

**Comment by mariusor** [comment]
Hey, thanx for this byt I can't approve it yet. So far fedbox doesn't really work if it's not exposed on HTTP as it needs to be accessible to activitypub clients and servers, because otherwise S2S activitypub doesn't work.

In the future I want fedbox to be mountable in go-littr as a package, so it won't need the server part.
It would be somthing like

```go
func (h *handler) Routes(c *config.Configuration) func(chi.Router) {
	return func(r chi.Router) {
		/* ... */
		r.Route("ap", fedbox.Routes())
	}
}
```

**Comment by squash** [comment]
The idea being that you would use the named unix socket to forward connections from a web server sitting in front of the container it runs in, rather than using tcp port. So it would still be fully accessible through the web server, but the communication between those two pieces would not be over tcp.

Caddyserver for example allows you to specify that proxy connection like such:
reverse_proxy * unix//var/run/socks/fedbox.sock

nginx has a similar function:
proxy_pass http://unix:/tmp/backend.socket:/uri/;

Having a predetermined named socket like this can make the setup a bit easier in cases where you're using a simple container strategy.

**Comment by mariusor** [comment]
I see, it makes sense. I'll do some investigation if I can use this with caddy and I'll report back.

**Comment by mariusor** [comment]
Could you please rebase on top of latest master so I can give it a try?

**Comment by squash** [comment]
Done

**Comment by mariusor** [comment]
Thank you for following up on this.

So, first of all I have some general comments on the code, I'm almost convinced to accept it:

### I would like a cleaner separation of the LISTEN cases. 

Currently if you have `HTTPS=true`, with valid `CERT_PATH` and `KEY_PATH` values the application doesn't start properly as it tries to listen on the socket, while enabling HTTP2. 

As I would like to switch from just using the `LISTEN` configuration to a `LISTEN_HOST`, `LISTEN_PORT` pair for the values, I would like to have a `LISTEN_PATH` maybe to simplify the logic.

2/ I will like to have documentation describing how this should be used, maybe with an example. 

### Testing

I haven't really managed to make this work (to my undying shame) in conjunction with caddy as it(caddy) seems to still try to load over HTTPS on the socket too, and I get 502 errors. The documentation would help me with that, if nothing else. :D

Thank you.

**Pull request closed without merging**
